INSERT INTO Videos VALUES(0, ''); 

INSERT INTO Comments VALUES(0, 'After been watching tons of thousands of Hollywood science fiction movies or superhero movies, I already had no interest or hope for Chinese film because of many reasons. But this one indeed blowed my mind and I just can''t wait to watch it again.

For all the years of development process that we''ve been counting on, Chinese film industry didn''t give us that many surprises but instead a lot of messed up things such as corruption and tax evasion. Sometimes even if we had a great script, there is no way to get enough funding on the right things because all the money was paid for those "data stars". There are lots of young and pretty stars that can drive huge customer data flow on the internet, they can easily earn millions of dollars just to appear in one movie. At the same time, what they can bring to the table was totally not enough for people to say they are a good actor, or even an actor.', 10.0, 0);

INSERT INTO Comments VALUES(0, 'Just watched the IMAX 3D movie. Trust me, don''t do it any other way. Imagine ten of thousands of fusion thrusters are pushing our planet away from a dying sun on a IMAX screen. The visual effect is impressive and goes well with the story. The story is not everyday Hollywood style: Superhero saves the day; everyone else is there to give a round of applause. This movie brings a serious question to the audience: What are you gonna do facing an unavoidable, irresistible disaster to our civilization? All characters in the movie are ordinary people and everyone gives their answer with shining humanity. Against all the odds no one gives in without a good fight. The chance of success is close to zero but they choose hope. All the efforts add up and make impossible nothing. It is a Sci-Fi fan''s feast you dont want to miss.', 10.0, 0);


INSERT INTO Comments VALUES(0, 'This is so far the best scifi Chinese movie i have ever seen. Honestly speaking, this movie is far more better than similar hollywood movies. if you are not sinophobia and can accept mostly chinese (with subtitle), it will not not let you regret.', 10.0, 0);

INSERT INTO Comments VALUES(0, 'After producing a string of sloppy, cringe-worthy sci-fi films, Chinese cinema has finally delivered one with awe-inspiring visual, and more surprisingly, a humanizing story.

For fans of hard sci-fi, this film''s premise is indeed a bit absurd and scientifically inaccurate; building ten thousand massive engines on the surface of earth to move the entire planet away from a dying sun. Still, the focus is not technology but people. The main plot focuses on grandfather, father and son (plus an adopted daughter) try to survive and preserve whatever dignity and humanity still remains on a chaotic frozen planet. The film hammers in the notion that anyone is somebody''s child, parent or best friend, yet a single human life is merely an incredibly expendable resource in the bigger picture. The visual effects are total eye-candy, but a generous amount of practical effects and realistic props are constant reminders of the setting''s ''earthiness''.', 9.0, 0);
